name: fida_rider
description: Fida-Ride passenger application.
version: 0.1.0+1
publish_to: none
resolution: workspace

environment:
  sdk: ^3.13.0
  flutter: '>=3.47.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  fida_api: ^0.1.0
  fida_location: ^0.1.0
  fida_security: ^0.1.0
  fida_ui: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
